version: '3.8'

services:
  tallerMecanico:
    image: taller-mecanico:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8109:8109"
    environment:
      - SPRING_DATA_MONGODB_URI:mongodb+srv://scala9207:7r0BxyIspALN1Ltl@sergio.k5srn4c.mongodb.net/tallerMecanico
